import { CreateInterviewData } from '@/types';

export interface InterviewTemplate extends CreateInterviewData {
  id: string;
  name: string;
  icon: string;
  tag: string;
}

export const INTERVIEW_TEMPLATES: InterviewTemplate[] = [
  {
    id: 'frontend',
    name: 'Frontend Developer',
    icon: '🖥️',
    tag: 'Technical',
    role: 'Frontend Developer',
    description: 'Proficiency in React, TypeScript, CSS, state management, performance optimization, accessibility, and modern build tooling.',
    experience_level: 'mid',
    difficulty: 'medium',
    duration: 30,
    interview_type: 'technical',
  },
  {
    id: 'backend',
    name: 'Backend Developer',
    icon: '⚙️',
    tag: 'Technical',
    role: 'Backend Developer',
    description: 'Server-side development with Node.js or Python, REST/GraphQL APIs, databases, caching, authentication, and system design.',
    experience_level: 'mid',
    difficulty: 'medium',
    duration: 30,
    interview_type: 'technical',
  },
  {
    id: 'fullstack',
    name: 'Full Stack Developer',
    icon: '🔥',
    tag: 'Technical',
    role: 'Full Stack Developer',
    description: 'End-to-end web development covering React frontend, Node.js backend, REST APIs, SQL/NoSQL databases, and cloud deployment.',
    experience_level: 'senior',
    difficulty: 'hard',
    duration: 45,
    interview_type: 'mixed',
  },
  {
    id: 'devops',
    name: 'DevOps / Cloud Engineer',
    icon: '☁️',
    tag: 'Infrastructure',
    role: 'DevOps Engineer',
    description: 'CI/CD pipelines, Docker, Kubernetes, AWS/GCP/Azure, infrastructure as code, monitoring, and site reliability engineering.',
    experience_level: 'senior',
    difficulty: 'hard',
    duration: 30,
    interview_type: 'technical',
  },
  {
    id: 'data-analyst',
    name: 'Data Analyst',
    icon: '📊',
    tag: 'Data',
    role: 'Data Analyst',
    description: 'SQL, Python for data analysis, data visualization with tools like Tableau or Power BI, statistical thinking, and business intelligence.',
    experience_level: 'mid',
    difficulty: 'medium',
    duration: 30,
    interview_type: 'technical',
  },
  {
    id: 'ml-engineer',
    name: 'ML Engineer',
    icon: '🤖',
    tag: 'AI/ML',
    role: 'Machine Learning Engineer',
    description: 'Machine learning fundamentals, model training and evaluation, Python, scikit-learn, PyTorch/TensorFlow, MLOps, and data pipelines.',
    experience_level: 'senior',
    difficulty: 'hard',
    duration: 45,
    interview_type: 'technical',
  },
  {
    id: 'mobile',
    name: 'Mobile Developer',
    icon: '📱',
    tag: 'Mobile',
    role: 'Mobile Developer',
    description: 'iOS/Android development using React Native or Flutter, mobile UI/UX patterns, state management, API integration, and app store deployment.',
    experience_level: 'mid',
    difficulty: 'medium',
    duration: 30,
    interview_type: 'technical',
  },
  {
    id: 'behavioral',
    name: 'Behavioral / Culture Fit',
    icon: '🎯',
    tag: 'Behavioral',
    role: 'Software Engineer',
    description: 'Teamwork, conflict resolution, time management, growth mindset, communication skills, leadership, and alignment with company values.',
    experience_level: 'mid',
    difficulty: 'easy',
    duration: 30,
    interview_type: 'behavioral',
  },
];
